# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: us-central1-docker.pkg.dev/kubernetes-428718/container-1/app1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /bhavya_PV_dir
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: host-pvc

---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer


---
# Persistent Volume Configuration
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: kubernetes-storage-disk
    fsType: ext4

---
# Persistent Volume Claim Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
