services:
  container1:
    # build: ./container1
    image: bhavya1712/container1
    ports:
      - "6000:6000"
    networks:
      - compose-networks
    volumes:
      - .:/storage

  container2:
  #  build: ./container2
   image: bhavya1712/container2 
   ports:
    - "7000:7000"
   networks:
    - compose-networks
   volumes:
    - .:/storage

networks:
  compose-networks:
    driver: bridge