apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: us-central1-docker.pkg.dev/kubernetes-428718/container-1/app2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /bhavya_PV_dir
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: host-pvc

---
# service for container 2

apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  
